services:
    damas:
        container_name: damas-core
        image: primcode/damas-core:latest
        volumes:
            - ./damas.json:/damas-core/server-nodejs/conf.json
            - ./www:/app/www
            - ./extensions:/app/extensions
        environment:
            DEBUG: "damas:*"
            HTTP_PORT: 8090
        depends_on:
            - mongo
        restart: always
        stdin_open: true
        tty: true
        build:
            context: ..
            dockerfile: docker/Dockerfile
    mongo:
        container_name: damas-mongo
        image: mongo:latest
        volumes:
            - ./db:/data/db
        restart: always
        stdin_open: true
        tty: true
    nginx:
        image: nginx
        container_name: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt/:/etc/letsencrypt/
        ports:
            - 80:80
            - 443:443
        depends_on:
            - damas
#        # add reverse proxy networks
#        # (multiple domains, one damas each)
#        networks:
#            - damas_default
